apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: supanuxtphile
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        client.knative.dev/user-image: us-central1-docker.pkg.dev/supanuxtphile-399200/supanuxtphile/supanuxtphile
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 424.0.0
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/supanuxtphile-399200/supanuxtphile/supanuxtphile
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
        env:
        - name: SUPABASE_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudnh4Z3F1bmxxdHR0cXhqYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODkyMTEzNzIsImV4cCI6MjAwNDc4NzM3Mn0.sk0z4ZA8j1rDfbSk2zNmiDIo65mqoZYVEzruDftZRQM
        - name: SUPABASE_URL
          value: https://vnvxxgqunlqtttqxjavc.supabase.co
        - name: SUPABASE_SERVICE_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudnh4Z3F1bmxxdHR0cXhqYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODkyMTEzNzIsImV4cCI6MjAwNDc4NzM3Mn0.sk0z4ZA8j1rDfbSk2zNmiDIo65mqoZYVEzruDftZRQM
        - name: SUPABASE_URI
          value: postgresql://postgres:UD_z*ekEEwR9Yc7dM6T6q_hr@db.vnvxxgqunlqtttqxjavc.supabase.co:5432/postgres

        - name: NUXT_PUBLIC_SUPABASE_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudnh4Z3F1bmxxdHR0cXhqYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODkyMTEzNzIsImV4cCI6MjAwNDc4NzM3Mn0.sk0z4ZA8j1rDfbSk2zNmiDIo65mqoZYVEzruDftZRQM
        - name: NUXT_PUBLIC_SUPABASE_URL
          value: https://vnvxxgqunlqtttqxjavc.supabase.co
        - name: NUXT_SUPABASE_SERVICE_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudnh4Z3F1bmxxdHR0cXhqYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODkyMTEzNzIsImV4cCI6MjAwNDc4NzM3Mn0.sk0z4ZA8j1rDfbSk2zNmiDIo65mqoZYVEzruDftZRQM
        - name: NUXT_SUPABASE_URI
          value: postgresql://postgres:UD_z*ekEEwR9Yc7dM6T6q_hr@db.vnvxxgqunlqtttqxjavc.supabase.co:5432/postgres
        - name: NUXT_SUPABASE_JWT_SECRET
          value: DJOzjSRDSTu67+ErTYVyddjrQ2o6OLa0OV46AH1Fhi4+Kr34NGWNAR9oYiubk0pUAvv3PR2QrnItF3S6UnRfTQ==
        - name: NUXT_RESEND_API_KEY
          value: re_Lo7iPvN3_CAdafk9TsfJmZRQhXzYLVUyo

        - name: NUXT_PUBLIC_GQL_HOST
          value: https://supanuxtphile-55dlfsvaeq-uc.a.run.app/api/graphql
        - name: NUXT_GQL_HOST
          value: https://supanuxtphile-55dlfsvaeq-uc.a.run.app/api/graphql
        - name: GQL_HOST
          value: https://supanuxtphile-55dlfsvaeq-uc.a.run.app/api/graphql

        - name: GRAPHQL_SCHEMAS
          value: todo,todo_api,app,app_api,msg,msg_api,inc,inc_api,loc,loc_api
        - name: NUXT_GRAPHQL_SCHEMAS
          value: todo,todo_api,app,app_api,msg,msg_api,inc,inc_api,loc,loc_api
      serviceAccountName: 757032130520-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
